/**
 * Math Solver Service
 * 
 * Handles all math-related operations:
 * - Send LaTeX expressions to AI solver
 * - Retrieve AI-generated solutions
 * - Manage solution caching and storage
 * Uses Gemini API for mathematical problem solving
 */

import { apiCall } from './api';

/**
 * Process mathematical expression using Gemini AI
 * Sends LaTeX formula to backend which calls Gemini API
 * @param {string} latex - Mathematical expression in LaTeX format
 * @returns {Promise<Object>} { success, solution, raw } or { success, error }
 */
export const processMath = async (latex) => {
  // Validate input before sending to API
  if (!latex || latex.trim() === '') {
    return {
      success: false,
      error: 'Please enter a mathematical expression',
    };
  }

  try {
    // Send LaTeX to backend for processing
    const response = await apiCall('/gemini/process', {
      method: 'POST',
      body: { latex },
    });

    // Parse AI response - Gemini returns candidates array
    if (response.ok && response.data.candidates) {
      const solutionText = response.data.candidates[0]?.content?.parts[0]?.text;
      
      // Return solution if AI provided one
      if (solutionText) {
        return {
          success: true,
          solution: solutionText,
          raw: response.data, // Keep raw response for debugging
        };
      }
    }

    // No solution generated by AI
    return {
      success: false,
      error: 'No solution found. Please try again.',
    };
  } catch (error) {
    console.error('Math processing error:', error);
    return {
      success: false,
      error: error.message || 'Error processing mathematical expression',
    };
  }
};

/**
 * Persist solution to session storage for retrieval on Solutions page
 * Uses session storage so data clears when browser closes
 * @param {string} latex - Original LaTeX expression
 * @param {string} solution - AI-generated solution text
 */
export const storeSolution = (latex, solution) => {
  // Store LaTeX expression
  sessionStorage.setItem('Latex', latex);
  // Store solution response
  sessionStorage.setItem('mathApiResponse', solution);
  // Keep original for reference
  sessionStorage.setItem('originalLatex', latex);
};

/**
 * Retrieve stored solution from session storage
 */
export const getStoredSolution = () => {
  const latex = sessionStorage.getItem('Latex');
  const solution = sessionStorage.getItem('mathApiResponse');
  
  if (!latex || !solution) {
    return null;
  }

  return { latex, solution };
};

/**
 * Clear stored solution
 */
export const clearStoredSolution = () => {
  sessionStorage.removeItem('Latex');
  sessionStorage.removeItem('mathApiResponse');
  sessionStorage.removeItem('originalLatex');
};
